version: '3.3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'blog'
      MYSQL_USER: 'vzincoder'
      MYSQL_PASSWORD: '12345678'
      MYSQL_ROOT_PASSWORD: '12345678'
    ports:
      - '3306:3306'
    expose: 
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: